#!/bin/bash

# Based (loosely) on example from https://docs.docker.com/engine/reference/builder/

/etc/init.d/unifi start || exit $?

trap "/etc/init.d/unifi stop" EXIT

echo "Run 'docker stop <container>' to exit"
while : ; do sleep 5 ; done
