#!/bin/bash

# Based (loosely) on example from https://docs.docker.com/engine/reference/builder/

UNIFI_USER="${UNIFI_USER:-unifi}"

chown -Rc "$UNIFI_USER" /var/{lib,log,run}/unifi

UNIFI_USER="$UNIFI_USER" /etc/init.d/unifi start || exit $?

trap "/etc/init.d/unifi stop" EXIT

echo "Run 'docker stop <container>' to exit"
while : ; do sleep 5 ; done
